on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Execute lint to verify errors
        run: npm run lint